spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

jwt:
  secret-key: as9b8aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl
  
app:
  frontend:
    url: http://localhost:5173
